{
 "title": "Monitoramento - AI Job Matcher",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Entrevistas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "interviews_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Acurácia",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "evaluation_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Média da Pontuação Geral",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "evaluation_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Média da Pontuação Técnica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "evaluation_technical_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Média da Pontuação de Comunicação",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "evaluation_communication_score", "legendFormat": "__auto" }
   ]
  }
 ]
}