{
 "title": "Monitoramento - AI Job Matcher",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Entrevistas",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "interviews_total" }
   ]
  },
  {
   "title": "Acurácia",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(interview_score_total / interviews_total) * 100"
    }
   ]
  },
  {
   "title": "Média da Pontuação Geral",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "interview_score_total / interviews_total",
     "legendFormat": "Pontuação Geral"
    }
   ]
  },
  {
   "title": "Média da Pontuação Técnica",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 4, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "interview_technical_score_total / interviews_total",
     "legendFormat": "Pontuação Técnica"
    }
   ]
  },
  {
   "title": "Média da Pontuação de Comunicação",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 4, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "interview_communication_score_total / interviews_total",
     "legendFormat": "Pontuação Comunicação"
    }
   ]
  }
 ]
}